import { Router } from "express";
import { signup, login } from "../controller/auth";
import dashboard from "../controller/createDocument";
import middleware from "../middleware/middleware";
import createDocument from "../controller/createDocument";
import joinDocument from "../controller/createDocument";
import showDocument from "../controller/showDocument";
const router: Router = Router();
router.post("/signup", signup);
router.post("/login", login);
router.get("/dashboard", middleware, dashboard);
router.post("/dashboard/createdocument", middleware, createDocument);
router.post("/joindocument", middleware, joinDocument);
router.post("/showDocument", middleware, showDocument);
export default router;
