FROM node:20-alpine

WORKDIR /app

# Enable pnpm
RUN corepack enable

# Copy root files
COPY . .
# Install dependencies
RUN pnpm install
# Build only api
RUN pnpm --filter=@repo/db exec prisma generate
RUN pnpm --filter=@repo/api build

# Run app
CMD ["node", "apps/api/dist/main.js"]